#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u https://github.com/Octavi-OS/platform_manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
#git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
#repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || 
repo sync -c -f --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j8

git clone $d -b 11 device/xiaomi/ulysse
#repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || 
repo sync -c -f --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8 

git clone $d -b 11 device/xiaomi/ulysse
git clone https://bitbucket.org/reisshxx/device_ulysse-common device/xiaomi/ulysse-common -b permissive
git clone https://bitbucket.org/reisshxx/vendor_ugg vendor/xiaomi/ugg
git clone https://bitbucket.org/reisshxx/vendor_ulysse-common vendor/xiaomi/ulysse-common
git clone https://github.com/adislice/android_kernel_xiaomi_msm8937/ --depth=1 -b em kernel/xiaomi/ulysse

rm -rf vendor/qcom/opensource/power
git clone https://github.com/Havoc-OS/android_vendor_qcom_opensource_power -b eleven vendor/qcom/opensource/power

cp kernel/xiaomi/ulysse/arch/arm64/configs/mi8* kernel/xiaomi/ulysse/arch/arm64/configs/ulysse_defconfig

rm -rf hardware/qcom-caf/wlan
git clone https://github.com/LineageOS/android_hardware_qcom_wlan -b lineage-18.1-caf hardware/qcom-caf/wlan

rm -rf vendor/qcom/opensource/dataservices
git clone https://github.com/NusantaraProject-ROM/android_vendor_qcom_opensource_dataservices -b 11 vendor/qcom/opensource/dataservices

rm -rf vendor/qcom/opensource/data-ipa-cfg-mgr
git clone https://github.com/LineageOS/android_vendor_qcom_opensource_data-ipa-cfg-mgr vendor/qcom/opensource/data-ipa-cfg-mgr
